### ISSUE TITLE
Especificacao de requisitos e casos de uso

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesAuthenticatorCoral#1]
Atualizar, com urgencia, os documentos de requisitos e casos de uso. Sem eles nao e possivel realizar VV&T.

**Comment by ghtravassos** [comment]
Falta o plano de projeto tambem! Urgente!

**Comment by Tuniks** [comment]
Plano de projeto e documentos de requisitos adicionados à aba Artefatos da Wiki. Casos de uso já estavam presentes.
