### ISSUE TITLE
Parâmetros para serviço pegar-preferencias

### ISSUE THREAD

**Issue by vitorcmaia** [ESEGroup/IssuesAuthenticatorCoral#10]
Identificamos pelo código presente em web.py o serviço http://35.199.79.158:8080/pegar-preferencias, desenvolvido com método POST. Este serviço espera parâmetro lab_id. Porém nosso POST retorna "vazio", inclusive sem informações raw.

Como este serviço deve ser chamado? E há parâmetros de autenticação para serem incluídos no Header?

**Comment by Tuniks** [comment]
O unico parametro pro pegar-preferencias é o lab_id = "1". O user_id vem da sessão.
