### ISSUE TITLE
Parâmetros para serviço registrar-presenca

### ISSUE THREAD

**Issue by vitorcmaia** [ESEGroup/IssuesAuthenticatorCoral#11]
O serviço http://35.199.79.158:8080/registrar-presenca (de acordo com o web.py) espera parâmetros "evento" e "lab_id". Evento por sua vez, pelo model, é um conjunto de campos epoch, evento, user_id, lab_id, nome_do_usuario. 

Poderia nos enviar um exemplo de chamada deste serviço? Precisamos, além do formato, de valores válidos de um usuário.

Não encontramos um serviço equivalente para a saída do laboratório, há algum?

**Comment by Tuniks** [comment]
/regsitrar-presença registra tanto a ausencia quanto a presença. Evento pode ser "IN" ou "OUT". "lab_id" temos o laboratório "1". Essas são as duas informações que devem ser enviados no request POST. Usuário ele pega do cookie autenticado.

**Comment by Tuniks** [comment]
Acredito que o unico usuario de laboratorio que temos cadastrado é o "tuniks". Usuarios de laboratorio não possuem senha.

**Comment by Tuniks** [comment]
Recomentando pois não sei se vc viu na outra Issue, hahaha: "Para usuario de sistema temos o usuario "osmar", senha "123". Não implementamos nenhuma função nova para ele, mas se quiserem cadastrar mais usuarios ou laboratorios, terão q usar esse login"
