### ISSUE TITLE
Login inicial do servidor

### ISSUE THREAD

**Issue by vitorcmaia** [ESEGroup/IssuesAuthenticatorCoral#12]
Em http://35.199.79.158:8080/login não termos um usuário de acesso (login e senha), poderia nos passar um valor padrão?

**Comment by vitorcmaia** [comment]
login tuniks,respondido em outra issue.

**Comment by Tuniks** [comment]
Para usuario de sistema temos o usuario "osmar", senha "123". Não implementamos nenhuma função nova para ele, mas se quiserem cadastrar mais usuarios ou laboratorios, terão q usar esse login
