### ISSUE TITLE
[Equipe de verificação] Consertar registro de inspeção dos requisitos 

### ISSUE THREAD

**Issue by Tuniks** [ESEGroup/IssuesAuthenticatorCoral#3]
O primeiro relatório de inspeção dos requisitos (arquivo REGISTRO DE INSPEÇÃO - Relatório de Diagnóstico Inicial de Inspeção - REQUISITOS_EquipeCoral_JB2017102216h07m) tem, na parte inferior do texto, uma série de correções para uma lista de requisitos que não é a do nosso trabalho.
Ela corrige requisitos funcionais até o número 20, nós não temos isso, e faz menções à Arduino, que também não usamos.
Posso estar entendendo errado, e há uma função para essa verificação, mas no momento ainda não está claro.

**Comment by vitorcmaia** [comment]
Estávamos com esta dúvida, recebemos dois documentos de requisitos, um maior e um menor. Na dúvida analisamos os dois. A partir de agora vamos ignorar o documento com 20 requisitos. Obrigado pela confirmação!

**Comment by Tuniks** [comment]
Desculpa pela confusão, não sei de onde surgiu esse arquivo surpresa.  Todos nossos artefatos se encontrão na wiki agora. Valeu!
