### ISSUE TITLE
Time VV&T: inspecionar artefatos atualizados

### ISSUE THREAD

**Issue by victor0machado** [ESEGroup/IssuesAuthenticatorCoral#4]

**Comment by vitorcmaia** [comment]
Adicionamos documentos de inspeção de requisitos e de planos de teste.
O plano do projeto com os requisitos está muito bom, mas os demais artefatos ainda estão desatualizados. O documento de casos de uso não bate com os requisitos em alguns pontos. É importante também incluir um diagrama de casos de uso, além das descrições.

**Comment by Tuniks** [comment]
Documento de caso de usos modificado para refletir as mudanças do projeto. Diagrama incluído.

**Comment by ghtravassos** [comment]
Nao consegui perceber onde estao os artefatos indicando resultados das inspecoes. Disponibilizar via wiki

**Comment by vitorcmaia** [comment]
@ghtravassos Disponibilizados na Wiki, no tópico "Inspeções."
@Tuniks Os documentos atualizados antes de ontem serão reanalisados o mais breve possível.

**Comment by vitorcmaia** [comment]
@Tuniks Enviamos o documento de inspeção dos casos de uso.

**Comment by jboarim** [comment]
Disponibilizaremos em breve uma versão 2 da inspeção de casos de uso.
