### ISSUE TITLE
Disponibilizar Webservice

### ISSUE THREAD

**Issue by vitorcmaia** [ESEGroup/IssuesAuthenticatorCoral#9]
O projeto já possui um WS? Gostaríamos de ter acesso para a execução de testes funcionais e testes de desempenho.

**Comment by vitorcmaia** [comment]
Identificamos o caminho http://35.199.100.176:8080/ como local deste servidor, mas a url parece não estar funcionando. Poderiam verificar?

**Comment by OsmarFFC** [comment]
Boa tarde, pessoal. O caminho teve que ser alterado para http://35.199.79.158:8080.
